server:
  error:
    include-stacktrace: on-param

spring:
#  h2:
#    console:
#      enabled: true
  datasource:
    # === h2
#    url: jdbc:h2:mem:patients-db
#    # === mysql
#    url: jdbc:mysql://localhost:3308/patients_db
##    username: root
##    password: root
#    username: patient_hub
#    password: Pass_24
#    driver-class-name: com.mysql.cj.jdbc.Driver

    # === postgres
    url: jdbc:postgresql://localhost:5432/patients_db
    username: patient_hub
    password: Pass_24
    driver-class-name: org.postgresql.Driver
  jpa:
#    database: MYSQL
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
