server:
  error:
    include-stacktrace: on-param

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  #  h2:
#    console:
#      enabled: true
  datasource:
    # === h2
#    url: jdbc:h2:mem:patients-db
#    # === mysql
#    url: jdbc:mysql://localhost:3308/patients_db
##    username: root
##    password: root
#    username: patient_hub
#    password: Pass_24
#    driver-class-name: com.mysql.cj.jdbc.Driver

    # === postgres
    url: jdbc:postgresql://localhost:5432/patients_db
    username: patient_hub
    password: Pass_24
    driver-class-name: org.postgresql.Driver
  jpa:
#    database: MYSQL
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      org.hibernate:
        # https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#envers
        envers:
#          default_schema: public
          use_revision_entity_with_native_id: true
          audit_strategy: org.hibernate.envers.strategy.internal.ValidityAuditStrategy
          audit_strategy_validity_store_revend_timestamp: true
#          track_entities_changed_in_revision: false
#          global_with_modified_flag: false

